# Server Port Config
server.port=${PORT:8080}

# Static Resources Mapping
spring.web.resources.static-locations=classpath:/static/

# Custom Firebase Config Settings
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH:classpath:serviceAccountKey.json}
firebase.credentials.json=${FIREBASE_CREDENTIALS:}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:8080,http://127.0.0.1:8080}

# Multipart Upload Constraints (Taha Jaffri Rule 8)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Console Logging Format & Levels (Taha Jaffri Rule 9)
logging.level.com.hemoconnect=INFO
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Strict JSON Schema Deserialization
spring.jackson.deserialization.fail-on-unknown-properties=true

# Dynamic Client configurations
firebase.client.apiKey=AIzaSyAEHoZ_AI2WY6U49mfFcMqRumucXaewl7A
firebase.client.authDomain=hemoconnect-22.firebaseapp.com
firebase.client.projectId=hemoconnect-22
firebase.client.storageBucket=hemoconnect-22.firebasestorage.app
firebase.client.messagingSenderId=1034879518806
firebase.client.appId=1:1034879518806:web:51cc08ab5acd964a2313f7
firebase.client.measurementId=G-35L1JDYQR0
google.maps.apiKey=AIzaSyDHemoConnectDefaultAPIKey_ReplaceWithRealKey

